### ISSUE TITLE
Update the WHC SWIO Flasher app for the SDK version 0.99 f7

### ISSUE THREAD

**Issue by furippa** [sukvojte/wch_swio_flasher#1]
Hello!

Your WHC SWIO Flasher app version `1.0` fails to build with the SDK version `0.99.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/6553299d3a6eebf5325ddff3/page)

Flipper Team

**Comment by sukvojte** [comment]
Fixed in 00c66bb914a640ca789b05874680d56d4a1fc388
